name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  main:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        scala:
          - 2.11.12
          - 2.12.15
          - 2.13.13
          - 2.13.14
          - 2.13.15
          - 3.3.3
          - 3.4.2
        java:
          - 11
          - 17
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: 'sbt'

      - name: Test
        run: |
          sbt ++${{ matrix.scala }} test
